import pandas as pd

def load_data():

    image_df = pd.read_csv(
        'mpeg7fex_win32_v2/img_data.txt', 
        sep=' ',
        names=[
                'name',
                'color_count',
                'spatial_coherency',
                'percentage_1',
                'centroid_1_channel1',
                'centroid_1_channel2',
                'centroid_1_channel3',
                'variance_1_channel1',
                'variance_1_channel2',
                'variance_1_channel3',
                'percentage_2',
                'centroid_2_channel1',
                'centroid_2_channel2',
                'centroid_2_channel3',
                'variance_2_channel1',
                'variance_2_channel2',
                'variance_2_channel3',
                'percentage_3',
                'centroid_3_channel1',
                'centroid_3_channel2',
                'centroid_3_channel3',
                'variance_3_channel1',
                'variance_3_channel2',
                'variance_3_channel3',
                'percentage_4',
                'centroid_4_channel1',
                'centroid_4_channel2',
                'centroid_4_channel3',
                'variance_4_channel1',
                'variance_4_channel2',
                'variance_4_channel3',
                'percentage_5',
                'centroid_5_channel1',
                'centroid_5_channel2',
                'centroid_5_channel3',
                'variance_5_channel1',
                'variance_5_channel2',
                'variance_5_channel3',
                'percentage_6',
                'centroid_6_channel1',
                'centroid_6_channel2',
                'centroid_6_channel3',
                'variance_6_channel1',
                'variance_6_channel2',
                'variance_6_channel3',
                'percentage_7',
                'centroid_7_channel1',
                'centroid_7_channel2',
                'centroid_7_channel3',
                'variance_7_channel1',
                'variance_7_channel2',
                'variance_7_channel3',
                'percentage_8',
                'centroid_8_channel1',
                'centroid_8_channel2',
                'centroid_8_channel3',
                'variance_8_channel1',
                'variance_8_channel2',
                'variance_8_channel3'
            ]   
        )

    return image_df

